#!/usr/bin/env bash
# Installation/uninstallation script for Millennium helper scripts.
set -euo pipefail

# Text color formatting
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

TARGET_DIR="/usr/local/bin"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SUDOERS_FILE="/etc/sudoers.d/millennium-helpers"

# Define scripts to manage (format: "source_filename:target_command_name")
SCRIPTS=(
  "scripts/millennium-repair.sh:millennium-repair"
  "scripts/millennium-upgrade-beta.sh:millennium-upgrade-beta"
  "scripts/millennium-upgrade-stable.sh:millennium-upgrade-stable"
  "scripts/millennium-schedule.sh:millennium-schedule"
  "scripts/millennium-purge.sh:millennium-purge"
  "scripts/millennium-diag.sh:millennium-diag"
)

show_help() {
  cat << EOF
Usage: $(basename "$0") [OPTIONS] [COMMAND]

Commands:
  install      Install scripts to ${TARGET_DIR} (default, requires sudo)
  uninstall    Remove scripts from ${TARGET_DIR} (requires sudo)

Options:
  -d, --dry-run      Perform dry-run without copying files or configuring sudoers
  -i, --install      Perform installation
  -u, --uninstall    Perform uninstallation
  -h, --help         Show this help message
EOF
}

check_root() {
  if [[ "$DRY_RUN" == "false" ]] && [[ "$(id -u)" -ne 0 ]]; then
    echo -e "${RED}Error: This script must be run with sudo to install system-wide to ${TARGET_DIR}.${NC}" >&2
    echo -e "Please run: sudo $0 $*" >&2
    exit 1
  fi
}

# Parse arguments
ACTION="install"
DRY_RUN=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    install|-i|--install)
      ACTION="install"
      shift
      ;;
    uninstall|-u|--uninstall)
      ACTION="uninstall"
      shift
      ;;
    -d|--dry-run)
      DRY_RUN=true
      shift
      ;;
    -h|--help)
      show_help
      exit 0
      ;;
    *)
      echo -e "${RED}Unknown argument: $1${NC}" >&2
      show_help
      exit 1
      ;;
  esac
done

check_root "$ACTION"

if [[ "$DRY_RUN" == "true" ]]; then
  echo -e "${YELLOW}=== DRY RUN MODE: No changes will be made ===${NC}"
fi

execute() {
  if [[ "$DRY_RUN" == "true" ]]; then
    echo -e "${YELLOW}[DRY RUN] Would run:${NC} $*"
  else
    "$@"
  fi
}

write_file() {
  local target="$1"
  if [[ "$DRY_RUN" == "true" ]]; then
    echo -e "${YELLOW}[DRY RUN] Would write file: ${target} with contents:${NC}"
    cat
  else
    cat > "$target"
  fi
}

install_scripts() {
  echo -e "${BLUE}Installing Millennium helper scripts to ${TARGET_DIR}...${NC}"

  for item in "${SCRIPTS[@]}"; do
    local src="${item%%:*}"
    local dest="${item#*:}"
    local src_path="${SCRIPT_DIR}/${src}"
    local dest_path="${TARGET_DIR}/${dest}"

    if [[ ! -f "$src_path" ]]; then
      echo -e "${RED}Error: Source script not found: ${src_path}${NC}" >&2
      exit 1
    fi

    # Copy script, set ownership to root, and make executable (755)
    echo "Installing: $dest_path"
    execute cp -f "$src_path" "$dest_path"
    execute chown root:root "$dest_path"
    execute chmod 755 "$dest_path"
  done

  # Configure passwordless sudoers rules in /etc/sudoers.d/millennium-helpers
  local user_name="${SUDO_USER:-$USER}"
  if [[ "$user_name" != "root" ]]; then
    echo -e "${BLUE}Configuring passwordless sudo rule in ${SUDOERS_FILE}...${NC}"
    
    # Ensure target directory exists and has secure permissions
    local sudoers_d_dir="$(dirname "$SUDOERS_FILE")"
    if [[ "$DRY_RUN" == "false" && ! -d "$sudoers_d_dir" ]]; then
      mkdir -p "$sudoers_d_dir"
      chmod 750 "$sudoers_d_dir"
      chown root:root "$sudoers_d_dir"
    elif [[ "$DRY_RUN" == "true" ]]; then
      echo -e "${YELLOW}[DRY RUN] Would ensure directory exists with 750 permissions:${NC} ${sudoers_d_dir}"
    fi

    write_file "$SUDOERS_FILE" << EOF
# Automatically generated by Millennium helpers installer. Do not edit manually.
${user_name} ALL=(ALL) NOPASSWD: /usr/local/bin/millennium-upgrade-stable, /usr/local/bin/millennium-upgrade-beta
EOF
    
    execute chmod 440 "$SUDOERS_FILE"
    execute chown root:root "$SUDOERS_FILE"

    # Validate sudoers configuration with visudo
    if [[ "$DRY_RUN" == "false" ]]; then
      if visudo -cf "$SUDOERS_FILE" &>/dev/null; then
        echo "Sudoers drop-in validated successfully."
        if command -v restorecon &>/dev/null; then
          restorecon "$SUDOERS_FILE" || true
        fi
      else
        echo -e "${RED}Error: Generated sudoers file is invalid. Reverting changes...${NC}" >&2
        rm -f "$SUDOERS_FILE"
        exit 1
      fi
    else
      echo -e "${YELLOW}[DRY RUN] Would validate sudoers file with visudo${NC}"
    fi
  else
    echo -e "${YELLOW}Running as root directly. Skipping passwordless sudo configuration.${NC}"
  fi

  # Clean up legacy local user symlinks if they exist
  local user_home
  user_home="$(getent passwd "$user_name" | cut -d: -f6)"
  local user_bin="${user_home}/.local/bin"

  if [[ -d "$user_bin" || "$DRY_RUN" == "true" ]]; then
    for item in "${SCRIPTS[@]}"; do
      local dest="${item#*:}"
      local legacy_path="${user_bin}/${dest}"
      if [[ -L "$legacy_path" || "$DRY_RUN" == "true" ]]; then
        echo "Removing legacy user symlink: $legacy_path"
        execute rm -f "$legacy_path"
      fi
    done
  fi

  if [[ "$DRY_RUN" == "true" ]]; then
    echo -e "${GREEN}Dry run completed successfully!${NC}"
  else
    echo -e "${GREEN}Installation completed successfully!${NC}"
    echo -e "\nYou can now run the scripts directly from your terminal:"
    for item in "${SCRIPTS[@]}"; do
      local dest="${item#*:}"
      echo -e "  - ${dest}"
    done
  fi
}

uninstall_scripts() {
  echo -e "${BLUE}Uninstalling Millennium helper scripts from ${TARGET_DIR}...${NC}"
  
  local removed_any=false
  for item in "${SCRIPTS[@]}"; do
    local dest="${item#*:}"
    local dest_path="${TARGET_DIR}/${dest}"

    if [[ -f "$dest_path" || "$DRY_RUN" == "true" ]]; then
      echo "Removing: $dest_path"
      execute rm -f "$dest_path"
      removed_any=true
    fi
  done

  if [[ -f "$SUDOERS_FILE" || "$DRY_RUN" == "true" ]]; then
    echo "Removing: $SUDOERS_FILE"
    execute rm -f "$SUDOERS_FILE"
    removed_any=true
  fi

  # Clean up systemd user timers/services for the invoking user
  local user_name="${SUDO_USER:-$USER}"
  if [[ "$user_name" != "root" ]]; then
    local user_home
    user_home="$(getent passwd "$user_name" | cut -d: -f6)"
    local user_systemd_dir="${user_home}/.config/systemd/user"
    
    if [[ -d "$user_systemd_dir" || "$DRY_RUN" == "true" ]]; then
      local timer_file="${user_systemd_dir}/millennium-update.timer"
      local service_file="${user_systemd_dir}/millennium-update.service"
      
      if [[ -f "$timer_file" || -f "$service_file" || "$DRY_RUN" == "true" ]]; then
        echo "Disabling and removing systemd user update timer/service..."
        execute runuser -l "$user_name" -c "systemctl --user disable --now millennium-update.timer" || true
        execute runuser -l "$user_name" -c "systemctl --user stop millennium-update.service" || true
        
        execute rm -f "$timer_file" "$service_file"
        execute runuser -l "$user_name" -c "systemctl --user daemon-reload" || true
        removed_any=true
      fi
    fi
  fi

  if [[ "$removed_any" == true || "$DRY_RUN" == "true" ]]; then
    echo -e "${GREEN}Uninstallation completed successfully!${NC}"
  else
    echo -e "${YELLOW}No installed scripts or configuration found to uninstall.${NC}"
  fi
}

case "$ACTION" in
  install)
    install_scripts
    ;;
  uninstall)
    uninstall_scripts
    ;;
esac
