# Dispatcher: millennium <command> [args...]
set -l __mh_cmds diag doctor upgrade schedule theme repair purge mcp install uninstall help

complete -c millennium -f -n "not __fish_seen_subcommand_from $__mh_cmds" -a 'diag' -d 'Run diagnostics'
complete -c millennium -f -n "not __fish_seen_subcommand_from $__mh_cmds" -a 'doctor' -d 'Alias for diag doctor'
complete -c millennium -f -n "not __fish_seen_subcommand_from $__mh_cmds" -a 'upgrade' -d 'Upgrade / install Millennium'
complete -c millennium -f -n "not __fish_seen_subcommand_from $__mh_cmds" -a 'schedule' -d 'Manage auto-update scheduler'
complete -c millennium -f -n "not __fish_seen_subcommand_from $__mh_cmds" -a 'theme' -d 'Manage skins/themes'
complete -c millennium -f -n "not __fish_seen_subcommand_from $__mh_cmds" -a 'repair' -d 'Repair hooks and ownership'
complete -c millennium -f -n "not __fish_seen_subcommand_from $__mh_cmds" -a 'purge' -d 'Uninstall Millennium'
complete -c millennium -f -n "not __fish_seen_subcommand_from $__mh_cmds" -a 'mcp' -d 'Run / register MCP server'
complete -c millennium -f -n "not __fish_seen_subcommand_from $__mh_cmds" -a 'install' -d 'Install helpers on this machine'
complete -c millennium -f -n "not __fish_seen_subcommand_from $__mh_cmds" -a 'uninstall' -d 'Remove helpers installed by millennium install'
complete -c millennium -f -n "not __fish_seen_subcommand_from $__mh_cmds" -a 'help' -d 'Show help'

# diag
complete -c millennium -f -n '__fish_seen_subcommand_from diag' -a 'doctor' -d 'Repair partial or broken installations'
complete -c millennium -f -n '__fish_seen_subcommand_from diag' -a 'logs' -d 'Show recent Millennium / Steam logs'
complete -c millennium -f -n '__fish_seen_subcommand_from diag' -l json -d 'JSON output'
complete -c millennium -f -n '__fish_seen_subcommand_from diag' -s f -l fix -d 'Alias for doctor'
complete -c millennium -f -n '__fish_seen_subcommand_from diag' -l force -d 'Force all doctor repairs'
complete -c millennium -f -n '__fish_seen_subcommand_from diag' -s l -l follow -d 'Follow real-time log output'
complete -c millennium -f -n '__fish_seen_subcommand_from diag' -s s -l share -d 'Upload diagnostic report'
complete -c millennium -f -n '__fish_seen_subcommand_from diag' -s y -l yes -d 'Skip Steam close confirmation'
complete -c millennium -f -n '__fish_seen_subcommand_from diag' -s d -l dry-run -d 'Simulation mode'
complete -c millennium -f -n '__fish_seen_subcommand_from diag' -s q -l quiet -d 'Suppress informational output'
complete -c millennium -f -n '__fish_seen_subcommand_from diag' -s h -l help -d 'Show help'

# upgrade
complete -c millennium -f -n '__fish_seen_subcommand_from upgrade' -s c -l channel -d 'Update channel' -a 'stable beta main'
complete -c millennium -f -n '__fish_seen_subcommand_from upgrade' -l stable -d 'Alias for --channel stable'
complete -c millennium -f -n '__fish_seen_subcommand_from upgrade' -l beta -d 'Alias for --channel beta'
complete -c millennium -f -n '__fish_seen_subcommand_from upgrade' -l main -d 'Alias for --channel main'
complete -c millennium -f -n '__fish_seen_subcommand_from upgrade' -s r -l rollback -d 'Roll back to a previous backup'
complete -c millennium -f -n '__fish_seen_subcommand_from upgrade' -l file -r -d 'Install from local archive'
complete -c millennium -f -n '__fish_seen_subcommand_from upgrade' -l sha256 -r -d 'Expected SHA-256 of --file archive'
complete -c millennium -f -n '__fish_seen_subcommand_from upgrade' -l insecure-skip-verify -d 'Skip archive checksum verification'
complete -c millennium -f -n '__fish_seen_subcommand_from upgrade' -l all-users -d 'Unix: apply install for all users'
complete -c millennium -f -n '__fish_seen_subcommand_from upgrade' -s f -l force -d 'Force reinstall'
complete -c millennium -f -n '__fish_seen_subcommand_from upgrade' -s y -l yes -d 'Skip Steam close confirmation'
complete -c millennium -f -n '__fish_seen_subcommand_from upgrade' -s d -l dry-run -d 'Simulation mode'
complete -c millennium -f -n '__fish_seen_subcommand_from upgrade' -s q -l quiet -d 'Suppress informational output'

# schedule
complete -c millennium -f -n '__fish_seen_subcommand_from schedule' -a 'enable disable status setup config' -d 'Schedule command'
complete -c millennium -f -n '__fish_seen_subcommand_from schedule; and __fish_seen_subcommand_from enable' -a 'stable beta main' -d 'Client update channel'
complete -c millennium -f -n '__fish_seen_subcommand_from schedule' -s c -l cron -d 'Force use of crontab instead of systemd'
complete -c millennium -f -n '__fish_seen_subcommand_from schedule' -l system -d 'Linux: force systemd system units'
complete -c millennium -f -n '__fish_seen_subcommand_from schedule' -l user -d 'Linux: force systemd user units'
complete -c millennium -f -n '__fish_seen_subcommand_from schedule' -s d -l dry-run -d 'Simulation mode'
complete -c millennium -f -n '__fish_seen_subcommand_from schedule' -s q -l quiet -d 'Suppress informational output'

# theme
complete -c millennium -f -n '__fish_seen_subcommand_from theme' -a 'list install update remove' -d 'Theme command'
complete -c millennium -f -n '__fish_seen_subcommand_from theme' -l json -d 'JSON list output'
complete -c millennium -f -n '__fish_seen_subcommand_from theme' -s y -l yes -d 'Skip remove confirmation'
complete -c millennium -f -n '__fish_seen_subcommand_from theme' -s d -l dry-run -d 'Simulation mode'
complete -c millennium -f -n '__fish_seen_subcommand_from theme' -s q -l quiet -d 'Suppress informational output'

# repair / purge / mcp
complete -c millennium -f -n '__fish_seen_subcommand_from repair' -s s -l skip-theme -d 'Skip theme refresh'
complete -c millennium -f -n '__fish_seen_subcommand_from repair' -s y -l yes -d 'Skip Steam close confirmation'
complete -c millennium -f -n '__fish_seen_subcommand_from repair' -s d -l dry-run -d 'Simulation mode'
complete -c millennium -f -n '__fish_seen_subcommand_from repair' -s q -l quiet -d 'Suppress informational output'
complete -c millennium -f -n '__fish_seen_subcommand_from purge' -s y -l yes -d 'Skip confirmation'
complete -c millennium -f -n '__fish_seen_subcommand_from purge' -s d -l dry-run -d 'Simulation mode'
complete -c millennium -f -n '__fish_seen_subcommand_from purge' -s q -l quiet -d 'Suppress informational output'
complete -c millennium -f -n '__fish_seen_subcommand_from mcp' -s r -l register -d 'Register with AI clients'

# install / uninstall
complete -c millennium -f -n '__fish_seen_subcommand_from install uninstall' -l track -r -a 'release main tag checkout' -d 'Helpers install track'
complete -c millennium -f -n '__fish_seen_subcommand_from install uninstall' -l tag -r -d 'Install a specific release tag'
complete -c millennium -f -n '__fish_seen_subcommand_from install uninstall' -l allow-unsigned-main -d 'Allow tip-of-main unsigned archive'
complete -c millennium -f -n '__fish_seen_subcommand_from install uninstall' -l prefix -r -d 'Binary install directory prefix'
complete -c millennium -f -n '__fish_seen_subcommand_from install uninstall' -l target-dir -r -d 'Binary install directory'
complete -c millennium -f -n '__fish_seen_subcommand_from install uninstall' -l lib-dir -r -d 'Unix lib directory'
complete -c millennium -f -n '__fish_seen_subcommand_from install uninstall' -l source-root -r -d 'Checkout or extracted archive root'
complete -c millennium -f -n '__fish_seen_subcommand_from install' -l skip-wizard -d 'Do not launch schedule setup'
complete -c millennium -f -n '__fish_seen_subcommand_from uninstall' -s p -l purge -d 'Also purge Millennium client'
complete -c millennium -f -n '__fish_seen_subcommand_from install uninstall' -s d -l dry-run -d 'Simulation mode'
complete -c millennium -f -n '__fish_seen_subcommand_from install' -s f -l force -d 'Force reinstall'
