complete -c millennium-upgrade -s f -l force -d 'Force reinstall'
complete -c millennium-upgrade -s d -l dry-run -d 'Simulation mode'
complete -c millennium-upgrade -s h -l help -d 'Show help message'
complete -c millennium-upgrade -s c -l channel -r -f -a 'stable beta' -d 'Update channel (stable/beta)'
complete -c millennium-upgrade -l stable -d 'Use stable channel'
complete -c millennium-upgrade -l beta -d 'Use beta channel'
complete -c millennium-upgrade -s r -l rollback -d 'Roll back to a previous version'
complete -c millennium-upgrade -l file -r -d 'Install from local archive'
