name: Homebrew Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  homebrew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Audit Formula
        run: |
          mkdir -p "$(brew --repository)/Library/Taps/local/homebrew-local/Formula"
          cp Formula/millennium-helpers.rb "$(brew --repository)/Library/Taps/local/homebrew-local/Formula/"
          brew audit --formula local/local/millennium-helpers
