name: "CI: Shell Script Linting"

on:
  push:
    branches: [ main ]
    paths:
      - '**.sh'
      - 'scripts/**'
      - 'install.sh'
      - '.github/workflows/shellcheck.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**.sh'
      - 'scripts/**'
      - 'install.sh'
      - '.github/workflows/shellcheck.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shellcheck:
    name: Run ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Run ShellCheck Lint
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: completions/ packaging/
